language: node_js
node_js:
  - "node" # Latest node version
  - "lts/*" # Latest LTS version
  - "10"
  - "8"
  - "6.10"

script:
   - node --version
   - npm --version
   - grunt standards
   - npm test
   - grunt build

deploy:
   provider: pages
   local-dir: dist
   skip-cleanup: true
   github-token: $GITHUB_TOKEN # Set in the settings page of the repository, as a secure variable
   committer-from-gh: true
   keep-history: true
   on:
      branch: master
      node: '8'

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
